from __future__ import annotations

from typing import TYPE_CHECKING, NamedTuple, Optional

from BaseClasses import ItemClassification, Location

from .Options import EndGoal, THAWOptions

class THAWLocation(Location):
    game = "Tony Hawk's American Wasteland"

class THAWLocData(NamedTuple):
    ap_code: Optional[int]
    region: Optional[str]

THAW_hollywood_locations = {
    # You can take a peak at Types.py for more information but,
    # THAWLocData is code, region in this instance
    # Regions will be explained more in Regions.py
    # But just know that it's mostly about organization
    # Place locations together based on where they are in the game and what is needed to get there
    # Hollywood Stage 1 Missions
    "HW Mission: Change Your Look": THAWLocData(10100001, "Hollywood"),
    "HW Mission: Change Your Clothes": THAWLocData(10100002, "Hollywood"),
    "HW Mission: Learn to Caveman": THAWLocData(10100003, "Hollywood"),
    "HW Mission: Do a Sponsor Challenge": THAWLocData(10100004, "Hollywood"),
    "HW Mission: Kickflip Whofleck": THAWLocData(10100005, "Hollywood"),
    "HW Mission: Learn to Revert": THAWLocData(10100006, "Hollywood"),
    "HW Mission: Get Your Stuff Back": THAWLocData(10100007, "Hollywood"),
    "HW Mission: Get Into Beverly Hills": THAWLocData(10100008, "Hollywood"),
    "HW Mission: First Tagging Mission": THAWLocData(10150001, "Hollywood"),
    "HW Mission: Second Tagging Mission": THAWLocData(10150002, "Hollywood"),
    "HW Mission: Third Tagging Mission": THAWLocData(10150003, "Hollywood"),
    "HW Mission: Fourth Tagging Mission": THAWLocData(10150004, "Hollywood"),
    "HW Mission: Fifth Tagging Mission": THAWLocData(10150005, "Hollywood"),
    # Hollywood Gaps
    "HW Gap: Bench2Bench": THAWLocData(10200001, "Hollywood"),
    "HW Gap: FireEscape Level1": THAWLocData(10200002, "Hollywood"),
    "HW Gap: Hollywood High Steps": THAWLocData(10200003, "Hollywood"),
    "HW Gap: Planter2Planter": THAWLocData(10200004, "Hollywood"),
    "HW Gap: Rail2Bleacher": THAWLocData(10200005, "Hollywood"),
    "HW Gap: Rail2Rail": THAWLocData(10200006, "Hollywood"),
    "HW Gap: Bleacher Hop": THAWLocData(10200007, "Hollywood"),
    "HW Gap: Car Hop": THAWLocData(10200008, "Hollywood"),
    "HW Gap: Chinese Transfer": THAWLocData(10200009, "Hollywood"),
    "HW Gap: El Teniente Spine": THAWLocData(10200010, "Hollywood"),
    "HW Gap: FireEscape Level2": THAWLocData(10200011, "Hollywood"),
    "HW Gap: Hollywood Sign Blast": THAWLocData(10200012, "Hollywood"),
    "HW Gap: Pin Plant": THAWLocData(10200013, "Hollywood"),
    "HW Gap: Planter Pop": THAWLocData(10200014, "Hollywood"),
    "HW Gap: Romperwood Spine": THAWLocData(10200015, "Hollywood"),
    "HW Gap: Romperwood Transfer": THAWLocData(10200016, "Hollywood"),
    "HW Gap: Schools Out": THAWLocData(10200017, "Hollywood"),
    "HW Gap: Tony to Tony": THAWLocData(10200018, "Hollywood"),
    "HW Gap: Velvet Rope": THAWLocData(10200019, "Hollywood"),
    "HW Gap: Voodoo Spine": THAWLocData(10200020, "Hollywood"),
    "HW Gap: Half Moon Grind": THAWLocData(10200021, "Hollywood"),
    "HW Gap: Straight Outta Bronson": THAWLocData(10200022, "Hollywood"),
    "HW Gap: Yellow": THAWLocData(10200023, "Hollywood"),
    "HW Gap: FireEscape Level3": THAWLocData(10200024, "Hollywood"),
    "HW Gap: Record Deal": THAWLocData(10200025, "Hollywood"),
    "HW Gap: Spinner": THAWLocData(10200026, "Hollywood"),
    "HW Gap: Dump Up": THAWLocData(10200027, "Hollywood"),
    "HW Gap: El Teniente Drop": THAWLocData(10200028, "Hollywood"),
    "HW Gap: Romper Rail": THAWLocData(10200029, "Hollywood"),
    "HW Gap: Bronson Backlog": THAWLocData(10200030, "Hollywood"),
    "HW Gap: Trapdoor": THAWLocData(10200031, "Hollywood"),
    "HW Gap: FireEscape Level4": THAWLocData(10200032, "Hollywood"),
    "HW Gap: Goat Whackin'": THAWLocData(10200033, "Hollywood"),
    "HW Gap: Manual the Stars": THAWLocData(10200034, "Hollywood"),
    "HW Gap: Over vine": THAWLocData(10200035, "Hollywood"),
    "HW Gap: FireEscape Level5": THAWLocData(10200036, "Hollywood"),
    "HW Gap: Hollywood High Line": THAWLocData(10200037, "Hollywood"),
}

THAW_hollywood_shop_locations = {
    # Shirts
        "HW Shirt: Tanktop": THAWLocData(10310001, "Hollywood Shops"), 
        "HW Shirt: Sleeveless": THAWLocData(10310002, "Hollywood Shops"),
        "HW Shirt: T-shirt": THAWLocData(10310003, "Hollywood Shops"),
        "HW Shirt: Long Sleeve T": THAWLocData(10310004, "Hollywood Shops"),
        "HW Shirt: Layered T": THAWLocData(10310005, "Hollywood Shops"),  
        "HW Shirt: Military Coat": THAWLocData(10310006, "Hollywood Shops"), 
        "HW Shirt: Sweater": THAWLocData(10310007, "Hollywood Shops"),
        "HW Shirt: Hoody": THAWLocData(10310008, "Hollywood Shops"),
        "HW Shirt: Zip Up Hoody": THAWLocData(10310009, "Hollywood Shops"),
        "HW Shirt: Leather Vest": THAWLocData(10310010, "Hollywood Shops"), 
        "HW Shirt: Leather Jacket 1": THAWLocData(10310011, "Hollywood Shops"), 
        "HW Shirt: Leather Jacket 2": THAWLocData(10310012, "Hollywood Shops"),
        "HW Shirt: Sleeveless Denim": THAWLocData(10310013, "Hollywood Shops"),
        "HW Shirt: Vans Jersey": THAWLocData(10310014, "Hollywood Shops"),
        "HW Shirt: Hawk Hoody": THAWLocData(10310015, "Hollywood Shops"), 
        "HW Shirt: Hawk Thunder": THAWLocData(10310016, "Hollywood Shops"), 
        "HW Shirt: Quiksilver Button-up": THAWLocData(10310017, "Hollywood Shops"),
        "HW Shirt: Quiksilver Hoody 1": THAWLocData(10310018, "Hollywood Shops"),
        "HW Shirt: Electric Corpo": THAWLocData(10310019, "Hollywood Shops"),
        "HW Shirt: Electric Electroseal": THAWLocData(10310020, "Hollywood Shops"), 
        "HW Shirt: Electric Plasma": THAWLocData(10310021, "Hollywood Shops"), 
        "HW Shirt: Blind Bat Reaper Hoody": THAWLocData(10310022, "Hollywood Shops"),
        "HW Shirt: Nixon Shirt 2": THAWLocData(10310023, "Hollywood Shops"),
        "HW Shirt: Independent Stage 9 T": THAWLocData(10310024, "Hollywood Shops"),
        "HW Shirt: Von Zipper Hoody": THAWLocData(10310025, "Hollywood Shops"), 
        "HW Shirt: Sessions Standard Issue Hoody": THAWLocData(10310026, "Hollywood Shops"), 
        "HW Shirt: Volcom Hoody": THAWLocData(10310027, "Hollywood Shops"),
        "HW Shirt: Famous Stars and Straps Shirt 2": THAWLocData(10310028, "Hollywood Shops"),
        # Pants 
        "HW Pants: Jeans": THAWLocData(10320001, "Hollywood Shops"),
        "HW Pants: Tight Jeans": THAWLocData(10320002, "Hollywood Shops"),
        "HW Pants: Jeans Ripped": THAWLocData(10320003, "Hollywood Shops"),
        "HW Pants: Plaid Pants": THAWLocData(10320004, "Hollywood Shops"),
        "HW Pants: Cargo Pants": THAWLocData(10320005, "Hollywood Shops"),
        "HW Pants: Leather Pants": THAWLocData(10320006, "Hollywood Shops"),
        "HW Pants: Plaid Shorts": THAWLocData(10320007, "Hollywood Shops"),
        "HW Pants: Cargo Shorts": THAWLocData(10320008, "Hollywood Shops"),
        "HW Pants: Bunch Shorts": THAWLocData(10320009, "Hollywood Shops"),
        "HW Pants: Camo Shorts": THAWLocData(10320010, "Hollywood Shops"),
        "HW Pants: Quiksilver Jeans": THAWLocData(10320011, "Hollywood Shops"),
        "HW Pants: Baker Jeans": THAWLocData(10320012, "Hollywood Shops"),
        "HW Pants: Hurley Icon Jeans": THAWLocData(10320013, "Hollywood Shops"),
        "HW Pants: DVS Jeans": THAWLocData(10320014, "Hollywood Shops"),
        "HW Pants: DC Aidan DX Jeans": THAWLocData(10320015, "Hollywood Shops"),
        # Deck Graphics
        "HW Deck: Almost Mullen 10 Stair": THAWLocData(10330001, "Hollywood Shops"),
        "HW Deck: Almost Daewon Peace": THAWLocData(10330002, "Hollywood Shops"),
        "HW Deck: Alva Blue Tile": THAWLocData(10330003, "Hollywood Shops"),
        "HW Deck: Alva N": THAWLocData(10330004, "Hollywood Shops"),
        "HW Deck: Antihero Green": THAWLocData(10330005, "Hollywood Shops"),
        "HW Deck: Baker Brand Logo": THAWLocData(10330006, "Hollywood Shops"),
        "HW Deck: Birdhouse Compass": THAWLocData(10330007, "Hollywood Shops"),
        "HW Deck: Birdhouse Falcon Yellow": THAWLocData(10330008, "Hollywood Shops"),
        "HW Deck: Birdhouse Icon": THAWLocData(10330009, "Hollywood Shops"),
        "HW Deck: Blind Original": THAWLocData(10330010, "Hollywood Shops"),
        "HW Deck: 5Boro-Cinco Barrios": THAWLocData(10330011, "Hollywood Shops"),
        "HW Deck: DGK Ultra": THAWLocData(10330012, "Hollywood Shops"),
        "HW Deck: Element Mike v Big Series": THAWLocData(10330013, "Hollywood Shops"),
        "HW Deck: Element Section": THAWLocData(10330014, "Hollywood Shops"),
        "HW Deck: Hook Ups": THAWLocData(10330015, "Hollywood Shops"),
        "HW Deck: World Ind Vallely Animal Man": THAWLocData(10330016, "Hollywood Shops"),
        "HW Deck: World Ind Vallely Snake": THAWLocData(10330017, "Hollywood Shops"),
        "HW Deck: Plan B Team 3-D": THAWLocData(10330018, "Hollywood Shops"),
        "HW Deck: Powell Peralta Cab": THAWLocData(10330019, "Hollywood Shops"),
        "HW Deck: Powell Peralta Mullen": THAWLocData(10330020, "Hollywood Shops"),
        "HW Deck: RDS 1": THAWLocData(10330021, "Hollywood Shops"),
        "HW Deck: The Firm Bobs Stencil": THAWLocData(10330022, "Hollywood Shops"),
        "HW Deck: World Industries 1": THAWLocData(10330023, "Hollywood Shops"),
        # Grip Tape
        "HW Grip Tape: Generic Cut": THAWLocData(10340001, "Hollywood Shops"),
        "HW Grip Tape: Solid": THAWLocData(10340002, "Hollywood Shops"),
        "HW Grip Tape: Razor's Edge": THAWLocData(10340003, "Hollywood Shops"),
        "HW Grip Tape: Equal": THAWLocData(10340004, "Hollywood Shops"),
        "HW Grip Tape: Slasher": THAWLocData(10340005, "Hollywood Shops"),
        "HW Grip Tape: Ye Old School": THAWLocData(10340006, "Hollywood Shops"),
        "HW Grip Tape: Hawk": THAWLocData(10340007, "Hollywood Shops"),
        # Elbow Pads
        "HW Elbow Pads: Elbow Pads": THAWLocData(10350001, "Hollywood Shops"),
        "HW Elbow Pads: Left Elbow Pad": THAWLocData(10350002, "Hollywood Shops"),
        "HW Elbow Pads: Right Elbow Pad": THAWLocData(10350003, "Hollywood Shops"),
        # Knee Pads
        "HW Knee Pads": THAWLocData(10360001, "Hollywood Shops"),
        # Shoes
        "HW Shoes: Skate Shoe 1": THAWLocData(10370001, "Hollywood Shops"),
        "HW Shoes: Combat Boots": THAWLocData(10370002, "Hollywood Shops"),
        "HW Shoes: Hi Tops": THAWLocData(10370003, "Hollywood Shops"),
        "HW Shoes: Hurley the Crown": THAWLocData(10370004, "Hollywood Shops"),
        "HW Shoes: Hurley Amp": THAWLocData(10370005, "Hollywood Shops"),
        "HW Shoes: Hurley Burnquist": THAWLocData(10370006, "Hollywood Shops"),
        "HW Shoes: DGK Workout Low - White on White": THAWLocData(10370007, "Hollywood Shops"),
        "HW Shoes: DGK Workout Low - Navy": THAWLocData(10370008, "Hollywood Shops"),
        "HW Shoes: DGK Williams": THAWLocData(10370009, "Hollywood Shops"),
        "HW Shoes: Globe Icon": THAWLocData(10370010, "Hollywood Shops"),
        "HW Shoes: Globe Finale": THAWLocData(10370011, "Hollywood Shops"),
        "HW Shoes: Globe Mullen Tensor": THAWLocData(10370012, "Hollywood Shops"),
        "HW Shoes: DVS Milan": THAWLocData(10370013, "Hollywood Shops"),
        "HW Shoes: DVS Kenyan": THAWLocData(10370014, "Hollywood Shops"),
        "HW Shoes: DVS Revival Splat": THAWLocData(10370015, "Hollywood Shops"),
        "HW Shoes: DVS Daewon": THAWLocData(10370016, "Hollywood Shops"),
        "HW Shoes: Vans Tony III TT/Fog": THAWLocData(10370017, "Hollywood Shops"),
        "HW Shoes: Vans Tony III Blk/Wht": THAWLocData(10370018, "Hollywood Shops"),
        "HW Shoes: Vans Tony III Grn/Blk": THAWLocData(10370019, "Hollywood Shops"),
        "HW Shoes: Vans Tony III Garg/Nvy": THAWLocData(10370020, "Hollywood Shops"),
        "HW Shoes: Vans Tony III Gry/Wht": THAWLocData(10370021, "Hollywood Shops"),
        "HW Shoes: Checkered": THAWLocData(10370022, "Hollywood Shops"),
        "HW Shoes: ES Anti-Social": THAWLocData(10370023, "Hollywood Shops"),
        "HW Shoes: ES K7": THAWLocData(10370024, "Hollywood Shops"),
        "HW Shoes: ES Accelerate": THAWLocData(10370025, "Hollywood Shops"),
        "HW Shoes: Emerica Crass": THAWLocData(10370026, "Hollywood Shops"),
        "HW Shoes: Emerica Felt": THAWLocData(10370027, "Hollywood Shops"),
        "HW Shoes: Emerica Reynolds 3": THAWLocData(10370028, "Hollywood Shops"),
        "HW Shoes: Etnies Bastien": THAWLocData(10370029, "Hollywood Shops"),
        "HW Shoes: Etnies Arto": THAWLocData(10370030, "Hollywood Shops"),
        "HW Shoes: Etnies Lo-cal": THAWLocData(10370031, "Hollywood Shops"),
        "HW Shoes: Quiksilver Hawk 1": THAWLocData(10370032, "Hollywood Shops"),
        "HW Shoes: Quiksilver Hawk 2": THAWLocData(10370033, "Hollywood Shops"),
        "HW Shoes: Adio Selego": THAWLocData(10370034, "Hollywood Shops"),
        "HW Shoes: Adio Jeremy Wray": THAWLocData(10370035, "Hollywood Shops"),
        "HW Shoes: Adio Brian Sumner": THAWLocData(10370036, "Hollywood Shops"),
        "HW Shoes: Adio Tony Hawk": THAWLocData(10370037, "Hollywood Shops"),
        "HW Shoes: Adio Viva Bam": THAWLocData(10370038, "Hollywood Shops"),
        "HW Shoes: Nike Airzoom 1": THAWLocData(10370039, "Hollywood Shops"),
        "HW Shoes: Nike Airzoom 2": THAWLocData(10370040, "Hollywood Shops"),
        "HW Shoes: DC Manteca": THAWLocData(10370041, "Hollywood Shops"),
        "HW Shoes: Element Fuji": THAWLocData(10370042, "Hollywood Shops"),
        # Socks
        "HW Socks: Knee High": THAWLocData(10380001, "Hollywood Shops"),
        "HW Socks: Medium": THAWLocData(10380002, "Hollywood Shops"),
        "HW Socks: Low": THAWLocData(10380003, "Hollywood Shops"),
        # Hair
        "HW Hair: Bald": THAWLocData(10390001, "Hollywood Shops"),
        "HW Hair: Buzzed": THAWLocData(10390002, "Hollywood Shops"),
        "HW Hair: Devil Lock": THAWLocData(10390003, "Hollywood Shops"),
        "HW Hair: Dead Guy Doo": THAWLocData(10390004, "Hollywood Shops"),
        "HW Hair: Mullet": THAWLocData(10390005, "Hollywood Shops"),
        "HW Hair: McSqueeb R": THAWLocData(10390006, "Hollywood Shops"),
        "HW Hair: McSqueeb L": THAWLocData(10390007, "Hollywood Shops"),
        "HW Hair: Mohawk A": THAWLocData(10390008, "Hollywood Shops"),
        "HW Hair: Mohawk B": THAWLocData(10390009, "Hollywood Shops"),
        "HW Hair: Liberty Spikes 1": THAWLocData(10390010, "Hollywood Shops"),
        "HW Hair: Liberty Spikes 2": THAWLocData(10390011, "Hollywood Shops"),
        "HW Hair: Spiked 1": THAWLocData(10390012, "Hollywood Shops"),
        "HW Hair: Spiked 2": THAWLocData(10390013, "Hollywood Shops"),
        "HW Hair: Fauxhawk": THAWLocData(10390014, "Hollywood Shops"),
        "HW Hair: Long": THAWLocData(10390015, "Hollywood Shops"),
        "HW Hair: Ponytail": THAWLocData(10390016, "Hollywood Shops"),
        "HW Hair: Afro": THAWLocData(10390017, "Hollywood Shops"),
        "HW Hair: Dreadlocks": THAWLocData(10390018, "Hollywood Shops"),
        "HW Hair: Pompadour": THAWLocData(10390019, "Hollywood Shops"),
        "HW Hair: Flat Top": THAWLocData(10390020, "Hollywood Shops"),
        "HW Hair: Pigtails": THAWLocData(10390021, "Hollywood Shops"),
        "HW Hair: Caesar": THAWLocData(10390022, "Hollywood Shops"),
        "HW Hair: Cornrows": THAWLocData(10390023, "Hollywood Shops"),
        "HW Hair: Medium": THAWLocData(10390024, "Hollywood Shops"),
        "HW Hair: Short": THAWLocData(10390025, "Hollywood Shops"),    
}

THAW_beverly_hills_locations = {
    "Visit Beverly Hills": THAWLocData(20000001, "Beverly Hills"),
    "Visit the Skate Ranch": THAWLocData(20000002, "Skate Ranch"),
    # Beverly Hills Stage 1 Missions
    "BH Mission: Learn the Natas Spin": THAWLocData(20100001, "Beverly Hills"),
    "BH Mission: Learn Parkour tricks": THAWLocData(20100002, "Beverly Hills"),
    "BH Mission: Learn Spines, Flips, Rolls, Acid Drops, Banks": THAWLocData(20100003, "Beverly Hills"),
    "BH Mission: Learn the Boneless and Boned Ollie": THAWLocData(20100004, "Beverly Hills"),
    "BH Mission: Learn some wall tricks": THAWLocData(20100005, "Beverly Hills"),
    # stage 2
    "BH Mission: Impress Murphy": THAWLocData(20100006, "Beverly Hills"),
    "BH Mission: Impress Boone": THAWLocData(20100007, "Beverly Hills"),
    "BH Mission: Impress Dave": THAWLocData(20100008, "Beverly Hills"),
    # tagging missions
    "BH Mission: First Tagging Mission": THAWLocData(20150009, "Beverly Hills"),
    "BH Mission: Second Tagging Mission": THAWLocData(20150010, "Beverly Hills"),
    "BH Mission: Third Tagging Mission": THAWLocData(20150011, "Beverly Hills"),
    "BH Mission: Fourth Tagging Mission": THAWLocData(20150012, "Beverly Hills"),
    "BH Mission: Fifth Tagging Mission": THAWLocData(20150013, "Beverly Hills"),
    # Beverly Hills Gaps
    "BH Gap: Rail hop": THAWLocData(20200001, "Beverly Hills"),
    "BH Gap: Ledge 2 Rail": THAWLocData(20200002, "Beverly Hills"),
    "BH Gap: Rail 2 Ledge": THAWLocData(20200003, "Beverly Hills"),
    "BH Gap: Car hop": THAWLocData(20200004, "Beverly Hills"),
    "BH Gap: Ted's Lip": THAWLocData(20200005, "Beverly Hills"),
    "BH Gap: Useless crap": THAWLocData(20200006, "Beverly Hills"),
    "BH Gap: Between the trees": THAWLocData(20200007, "Beverly Hills"),
    "BH Gap: Going the distance": THAWLocData(20200008, "Beverly Hills"),
    "BH Gap: Rail 2 QP": THAWLocData(20200009, "Beverly Hills"),
    "BH Gap: Ramp 2 wire": THAWLocData(20200010, "Beverly Hills"),
    #"BH Gap: Short turd drop": THAWLocData(20200011, "Beverly Hills"),
    #"BH Gap: Upper ledge": THAWLocData(20200012, "Beverly Hills"),
    "BH Gap: Across the street": THAWLocData(20200013, "Beverly Hills"),
    "BH Gap: Alley transfer": THAWLocData(20200014, "Beverly Hills"),
    "BH Gap: Andys happy place": THAWLocData(20200015, "Beverly Hills"),
    "BH Gap: City hall transfer": THAWLocData(20200016, "Beverly Hills"),
    "BH Gap: Easy gap": THAWLocData(20200017, "Beverly Hills"),
    "BH Gap: Got Gas?": THAWLocData(20200018, "Beverly Hills"),
    #"BH Gap: Modern art?": THAWLocData(20200019, "Beverly Hills"),
    "BH Gap: Roof 2 roof": THAWLocData(20200020, "Beverly Hills"),
    #"BH Gap: No Tea baggin": THAWLocData(20200021, "Beverly Hills"),
    #"BH Gap: Out by 7!!": THAWLocData(20200022, "Beverly Hills"),
    "BH Gap: Ledge 2 awning": THAWLocData(20200023, "Beverly Hills"),
    #"BH Gap: Long turd drop": THAWLocData(20200024, "Beverly Hills"),
    "BH Gap: Qp 2 wire hop": THAWLocData(20200025, "Beverly Hills"),
    "BH Gap: Frontside entrance transfer": THAWLocData(20200026, "Beverly Hills"),
    "BH Gap: Got wings?": THAWLocData(20200027, "Beverly Hills"),
    "BH Gap: Nice manual": THAWLocData(20200028, "Beverly Hills"),
    #"BH Gap: Ralphs transfer": THAWLocData(20200029, "Beverly Hills"),
    "BH Gap: Gas 2 rail": THAWLocData(20200030, "Beverly Hills"),
    "BH Gap: Sweet stairset": THAWLocData(20200031, "Beverly Hills"),
    "BH Gap: Get your pizza": THAWLocData(20200032, "Beverly Hills"),
    "BH Gap: Wall 2 wire": THAWLocData(20200033, "Beverly Hills"),
    #"BH Gap: Learn to swim": THAWLocData(20200034, "Beverly Hills"),
}

THAW_beverly_hills_shop_locations = {
    # Shirts
    "BH Shirt: Ringer T": THAWLocData(20310001, "Beverly Hills Shops"),
    "BH Shirt: Polo Shirt": THAWLocData(20310002, "Beverly Hills Shops"),
    "BH Shirt: Baseball 1": THAWLocData(20310003, "Beverly Hills Shops"),
    "BH Shirt: Sports Coat": THAWLocData(20310004, "Beverly Hills Shops"),
    "BH Shirt: Dress Beater": THAWLocData(20310005, "Beverly Hills Shops"),
    "BH Shirt: Dress Shirt T": THAWLocData(20310006, "Beverly Hills Shops"),
    "BH Shirt: Denim Jacket": THAWLocData(20310007, "Beverly Hills Shops"),
    "BH Shirt: Track Jacket": THAWLocData(20310008, "Beverly Hills Shops"),
    "BH Shirt: Basketball Jersey": THAWLocData(20310009, "Beverly Hills Shops"),
    "BH Shirt: Hawaiian": THAWLocData(20310010, "Beverly Hills Shops"),
    "BH Shirt: Vans Birdseye": THAWLocData(20310011, "Beverly Hills Shops"),
    "BH Shirt: Hawk Brigade": THAWLocData(20310012, "Beverly Hills Shops"),
    "BH Shirt: Hawk Rocker": THAWLocData(20310013, "Beverly Hills Shops"),
    "BH Shirt: Quiksilver Striped": THAWLocData(20310014, "Beverly Hills Shops"),
    "BH Shirt: Quiksilver Hoody 2": THAWLocData(20310015, "Beverly Hills Shops"),
    "BH Shirt: Hurley Biker Jacket": THAWLocData(20310016, "Beverly Hills Shops"),
    "BH Shirt: Hurley Polo": THAWLocData(20310017, "Beverly Hills Shops"),
    "BH Shirt: DC Stence Tank": THAWLocData(20310018, "Beverly Hills Shops"),
    "BH Shirt: Element Baroque": THAWLocData(20310019, "Beverly Hills Shops"),
    "BH Shirt: Element Addict": THAWLocData(20310020, "Beverly Hills Shops"),
    "BH Shirt: Element Ardent": THAWLocData(20310021, "Beverly Hills Shops"),
    "BH Shirt: Electric Hoody": THAWLocData(20310022, "Beverly Hills Shops"),
    "BH Shirt: Nixon Shirt 1": THAWLocData(20310023, "Beverly Hills Shops"),
    "BH Shirt: Birdhouse Shirt 1": THAWLocData(20310024, "Beverly Hills Shops"),
    "BH Shirt: Alva OG Shirt": THAWLocData(20310025, "Beverly Hills Shops"),
    "BH Shirt: Von Zipper Shirt 1": THAWLocData(20310026, "Beverly Hills Shops"),
    "BH Shirt: Volcom Houston": THAWLocData(20310027, "Beverly Hills Shops"),
    "BH Shirt: Free Agent Shirt 1": THAWLocData(20310028, "Beverly Hills Shops"),
    "BH Shirt: Globe Quaranteen T": THAWLocData(20310029, "Beverly Hills Shops"),
    "BH Shirt: Panda Suit": THAWLocData(20310030, "Beverly Hills Shops"),
    # Pants
    "BH Pants: Khaki Pants": THAWLocData(20320001, "Beverly Hills Shops"),
    "BH Pants: Board Shorts": THAWLocData(20320002, "Beverly Hills Shops"),
    "BH Pants: Short Shorts": THAWLocData(20320003, "Beverly Hills Shops"),
    # Deck Graphics
    "BH Deck: Almost Sheckler Hate": THAWLocData(20330001, "Beverly Hills Shops"),
    "BH Deck: Alva Cross": THAWLocData(20330002, "Beverly Hills Shops"),
    "BH Deck: Alva Ocean Size": THAWLocData(20330003, "Beverly Hills Shops"),
    "BH Deck: Birdhouse Dragon Skull": THAWLocData(20330004, "Beverly Hills Shops"),
    "BH Deck: Birdhouse Giant Black": THAWLocData(20330005, "Beverly Hills Shops"),
    "BH Deck: Blind Reaper": THAWLocData(20330006, "Beverly Hills Shops"),
    "BH Deck: 5Boro Script Logo": THAWLocData(20330007, "Beverly Hills Shops"),
    "BH Deck: DGK Logo": THAWLocData(20330008, "Beverly Hills Shops"),
    "BH Deck: Element Bam Margera Big Series": THAWLocData(20330009, "Beverly Hills Shops"),
    "BH Deck: Element Elemental Seal": THAWLocData(20330010, "Beverly Hills Shops"),
    "BH Deck: Blind Chainsaw Kitten": THAWLocData(20330011, "Beverly Hills Shops"),
    "BH Deck: Plan B Team Bow Wow": THAWLocData(20330012, "Beverly Hills Shops"),
    "BH Deck: Powell Peralta Hawk": THAWLocData(20330013, "Beverly Hills Shops"),
    "BH Deck: RDS 2": THAWLocData(20330014, "Beverly Hills Shops"),
    "BH Deck: World Industries 2": THAWLocData(20330015, "Beverly Hills Shops"),
    # Grip Tape
    "BH Grip Tape: Striper": THAWLocData(20340001, "Beverly Hills Shops"),
    "BH Grip Tape: Thrashed": THAWLocData(20340002, "Beverly Hills Shops"),
    "BH Grip Tape: Colored Nuts": THAWLocData(20340003, "Beverly Hills Shops"),
    "BH Grip Tape: Green Machine": THAWLocData(20340004, "Beverly Hills Shops"),
    "BH Grip Tape: Blues": THAWLocData(20340005, "Beverly Hills Shops"),
    "BH Grip Tape: Red Light": THAWLocData(20340006, "Beverly Hills Shops"),
    "BH Grip Tape: Crack": THAWLocData(20340007, "Beverly Hills Shops"),
    "BH Grip Tape: Eye Don't Know": THAWLocData(20340008, "Beverly Hills Shops"),
    "BH Grip Tape: NS Single Eye": THAWLocData(20340009, "Beverly Hills Shops"),
    "BH Grip Tape: The Bat": THAWLocData(20340010, "Beverly Hills Shops"),
    "BH Grip Tape: Right Thrashed": THAWLocData(20340011, "Beverly Hills Shops"),
    "BH Grip Tape: Mullen": THAWLocData(20340012, "Beverly Hills Shops"),
    "BH Grip Tape: Sheckler": THAWLocData(20340013, "Beverly Hills Shops"),
    # Shoes
    "BH Shoes: Vans Tony III": THAWLocData(20350001, "Beverly Hills Shops"),
    "BH Shoes: Emerica Reynolds 2": THAWLocData(20350002, "Beverly Hills Shops"),
    # Left Accessory
    "BH Left Accessory: Wrist Band A": THAWLocData(20360001, "Beverly Hills Shops"),
    "BH Left Accessory: Watch A": THAWLocData(20360002, "Beverly Hills Shops"),
    "BH Left Accessory: Baker Die-Cut": THAWLocData(20360003, "Beverly Hills Shops"),
    "BH Left Accessory: DGK Baller Band": THAWLocData(20360004, "Beverly Hills Shops"),
    "BH Left Accessory: Nixon Player": THAWLocData(20360005, "Beverly Hills Shops"),
    "BH Left Accessory: Nixon Dork": THAWLocData(20360006, "Beverly Hills Shops"),
    "BH Left Accessory: Nixon Special Ops": THAWLocData(20360007, "Beverly Hills Shops"),
    "BH Left Accessory: Nixon Rocker": THAWLocData(20360008, "Beverly Hills Shops"),
    "BH Left Accessory: Nixon Band": THAWLocData(20360009, "Beverly Hills Shops"),
    "BH Left Accessory: Quiksilver Watch": THAWLocData(20360010, "Beverly Hills Shops"),
    "BH Left Accessory: Wristguard": THAWLocData(20360011, "Beverly Hills Shops"),
    "BH Left Accessory: Spikes": THAWLocData(20360012, "Beverly Hills Shops"),
    # Right Accessory
    "BH Right Accessory: Wrist Band A": THAWLocData(20370001, "Beverly Hills Shops"),
    "BH Right Accessory: Watch A": THAWLocData(20370002, "Beverly Hills Shops"),
    "BH Right Accessory: Baker Die-Cut": THAWLocData(20370003, "Beverly Hills Shops"),
    "BH Right Accessory: DGK Baller Band": THAWLocData(20370004, "Beverly Hills Shops"),
    "BH Right Accessory: Nixon Player": THAWLocData(20370005, "Beverly Hills Shops"),
    "BH Right Accessory: Nixon Dork": THAWLocData(20370006, "Beverly Hills Shops"),
    "BH Right Accessory: Nixon Special Ops": THAWLocData(20370007, "Beverly Hills Shops"),
    "BH Right Accessory: Nixon Rocker": THAWLocData(20370008, "Beverly Hills Shops"),
    "BH Right Accessory: Nixon Band": THAWLocData(20370009, "Beverly Hills Shops"),
    "BH Right Accessory: Quiksilver Watch": THAWLocData(20370010, "Beverly Hills Shops"),
    "BH Right Accessory: Wristguard": THAWLocData(20370011, "Beverly Hills Shops"),
    "BH Right Accessory: Spikes": THAWLocData(20370012, "Beverly Hills Shops"),
    # Gloves
    "BH Gloves: Glove 1": THAWLocData(20380001, "Beverly Hills Shops"),
    "BH Gloves: Glove 2": THAWLocData(20380002, "Beverly Hills Shops"),
    # Backpacks
    "BH Backpack: Backpack A": THAWLocData(20390001, "Beverly Hills Shops"),
    "BH Backpack: Backpack B": THAWLocData(20390002, "Beverly Hills Shops"),
    "BH Backpack: Messenger Bag": THAWLocData(20390003, "Beverly Hills Shops"),
    "BH Backpack: Backpack Paint": THAWLocData(20390004, "Beverly Hills Shops"),
    # Hats
    "BH Hats: Flatbilled Cap": THAWLocData(20391001, "Beverly Hills Shops"),
    "BH Hats: Baseball Cap": THAWLocData(20391002, "Beverly Hills Shops"),
    "BH Hats: Cap Backwards": THAWLocData(20391003, "Beverly Hills Shops"),
    "BH Hats: Upturned Bill": THAWLocData(20391004, "Beverly Hills Shops"),
    "BH Hats: Trucker Hat": THAWLocData(20391005, "Beverly Hills Shops"),
    "BH Hats: Trucker Backwards": THAWLocData(20391006, "Beverly Hills Shops"),
    "BH Hats: Brimmed Beanie": THAWLocData(20391007, "Beverly Hills Shops"),
    "BH Hats: Headband": THAWLocData(20391008, "Beverly Hills Shops"),
    "BH Hats: Visor": THAWLocData(20391009, "Beverly Hills Shops"),
    "BH Hats: Baker Hanoi A": THAWLocData(20391010, "Beverly Hills Shops"),
    "BH Hats: Baker Hanoi B": THAWLocData(20391011, "Beverly Hills Shops"),
    "BH Hats: Hurley Rude Boy": THAWLocData(20391012, "Beverly Hills Shops"),
    "BH Hats: DGK Headband": THAWLocData(20391013, "Beverly Hills Shops"),
    "BH Hats: DGK Cap 1": THAWLocData(20391014, "Beverly Hills Shops"),
    "BH Hats: DGK Cap 2": THAWLocData(20391015, "Beverly Hills Shops"),
    "BH Hats: DVS Trucker": THAWLocData(20391016, "Beverly Hills Shops"),
    "BH Hats: Electric Cap": THAWLocData(20391017, "Beverly Hills Shops"),
    "BH Hats: Pro-Tec Hassan": THAWLocData(20391018, "Beverly Hills Shops"),
    "BH Hats: Pro-Tec Lasek": THAWLocData(20391019, "Beverly Hills Shops"),
    "BH Hats: Pro-Tec Caballero": THAWLocData(20391020, "Beverly Hills Shops"),
    "BH Hats: Nixon Cap": THAWLocData(20391021, "Beverly Hills Shops"),
    "BH Hats: Quiksilver Cap 1": THAWLocData(20391022, "Beverly Hills Shops"),
    "BH Hats: Quiksilver Cap 2": THAWLocData(20391023, "Beverly Hills Shops"),
    "BH Hats: Birdhouse Cap 1": THAWLocData(20391024, "Beverly Hills Shops"),
    "BH Hats: Birdhouse Cap 2": THAWLocData(20391025, "Beverly Hills Shops"),
    "BH Hats: Alva Scratch Cap": THAWLocData(20391026, "Beverly Hills Shops"),
    "BH Hats: Zumiez Cap": THAWLocData(20391027, "Beverly Hills Shops"),
    "BH Hats: Indy Red/White Cross": THAWLocData(20391028, "Beverly Hills Shops"),
    "BH Hats: Plan B Cap 1": THAWLocData(20391029, "Beverly Hills Shops"),
    "BH Hats: Plan B Cap 2": THAWLocData(20391030, "Beverly Hills Shops"),
    "BH Hats: Sessions Kimballotta Cap": THAWLocData(20391031, "Beverly Hills Shops"),
    "BH Hats: RDS Cap": THAWLocData(20391032, "Beverly Hills Shops"),
    "BH Hats: Nike Cap": THAWLocData(20391033, "Beverly Hills Shops"),
    "BH Hats: Volcom Premium Cheese": THAWLocData(20391034, "Beverly Hills Shops"),
    "BH Hats: Volcom Cap": THAWLocData(20391035, "Beverly Hills Shops"),
    "BH Hats: Famous Stars and Straps Headband": THAWLocData(20391036, "Beverly Hills Shops"),
    "BH Hats: Free Agent Beanie": THAWLocData(20391037, "Beverly Hills Shops"),
    "BH Hats: Free Agent Trucker": THAWLocData(20391038, "Beverly Hills Shops"),
    "BH Hats: Globe Colab": THAWLocData(20391039, "Beverly Hills Shops"),
    # Glasses
    "BH Glasses: Aviator": THAWLocData(20392001, "Beverly Hills Shops"),
    "BH Glasses: Electric BSG": THAWLocData(20392002, "Beverly Hills Shops"),
    "BH Glasses: Arnette 1": THAWLocData(20392003, "Beverly Hills Shops"),
    "BH Glasses: Arnette 2": THAWLocData(20392004, "Beverly Hills Shops"),
    "BH Glasses: Arnette 3": THAWLocData(20392005, "Beverly Hills Shops"),
    "BH Glasses: Arnette 4": THAWLocData(20392006, "Beverly Hills Shops"),
    "BH Glasses: Von Zipper Papa G": THAWLocData(20392007, "Beverly Hills Shops"),
    "BH Glasses: Von Zipper Rockford": THAWLocData(20392008, "Beverly Hills Shops"),
    "BH Glasses: Von Zipper Brooklyn": THAWLocData(20392009, "Beverly Hills Shops"),
    "BH Glasses: Von Zipper Skitch": THAWLocData(20392010, "Beverly Hills Shops"),
}

endgoal_t_rex_locations = {
    "Smash the T-Rex": THAWLocData(None, "Hollywood")
}

endgoal_skate_ranch_locations = {
    "Get to the Skate Ranch": THAWLocData(None, "Beverly Hills")
}

#general locations
all_location_table = {
    **THAW_hollywood_locations,
    **THAW_hollywood_shop_locations,
    **THAW_beverly_hills_locations,
    **THAW_beverly_hills_shop_locations,
    **endgoal_t_rex_locations,
    **endgoal_skate_ranch_locations,
}

#feeds into gen
def setup_locations(options: THAWOptions):
    temp_location_table = {}
    if options.end_goal == options.end_goal.option_get_to_the_skate_ranch:
        temp_location_table.update({**endgoal_skate_ranch_locations})
        temp_location_table.update({**THAW_beverly_hills_locations})
        temp_location_table.update({**THAW_beverly_hills_shop_locations})
    if options.end_goal == options.end_goal.option_smash_the_t_rex:
        temp_location_table.update({**endgoal_t_rex_locations})
    temp_location_table.update({**THAW_hollywood_locations})
    temp_location_table.update({**THAW_hollywood_shop_locations})
    return temp_location_table